name: dayen_madeen
description: نظام إدارة الديون الاحترافي مع Firebase
version: 1.0.1+2

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter

  # إدارة الحالة والتنقل
  get: ^4.6.6
  get_storage: ^2.1.1

  # Firebase - الحزمة الكاملة للتطبيق المتكامل
  firebase_core: ^3.6.0                    # النواة الأساسية
  firebase_auth: ^5.3.1                    # المصادقة
  cloud_firestore: ^5.4.3                 # قاعدة البيانات
  firebase_messaging: ^15.1.3             # الإشعارات
  firebase_analytics: ^11.3.3             # التحليلات
  firebase_crashlytics: ^4.1.3            # تقارير الأخطاء
  firebase_performance: ^0.10.0+8         # مراقبة الأداء
  firebase_remote_config: ^5.1.3          # التحكم عن بعد
  firebase_storage: ^12.3.2               # تخزين الملفات

  # التصميم والواجهة
  google_fonts: ^6.2.1          # للخطوط العربية
  flutter_svg: ^2.0.10          # للأيقونات SVG
  cached_network_image: ^3.3.1  # تحميل وحفظ الصور
  shimmer: ^3.0.0               # تأثيرات التحميل
  lottie: ^3.1.2                # رسوم متحركة

  # المصادقة والأمان
  local_auth: ^2.1.8            # البصمة والمصادقة
  crypto: ^3.0.3                # التشفير
  google_sign_in: ^6.2.1        # تسجيل الدخول عبر Google

  # الإشعارات
  flutter_local_notifications: ^17.2.3  # إشعارات محلية
  timezone: ^0.9.4                      # لتوقيت الإشعارات

  # الطباعة والتصدير
  printing: ^5.12.0             # طباعة التقارير
  share_plus: ^7.2.2            # مشاركة الملفات
  pdf: ^3.10.8                  # إنشاء PDF

  # التحقق والتصديق
  email_validator: ^2.1.17     # التحقق من البريد

  # التصدير والاستيراد
  excel: ^4.0.6                # ملفات Excel
  csv: ^6.0.0                  # ملفات CSV
  file_picker: ^8.0.0+1        # اختيار الملفات
  permission_handler: ^11.3.1  # أذونات النظام
  path_provider: ^2.1.2        # مسارات النظام

  # معلومات الجهاز
  device_info_plus: ^10.1.2     # معلومات الجهاز
  connectivity_plus: ^6.0.5     # حالة الاتصال
  package_info_plus: ^8.0.2     # معلومات التطبيق

  # أدوات مساعدة
  intl: ^0.19.0                 # توطين وتنسيق
  url_launcher: ^6.2.5          # فتح الروابط
  image_picker: ^1.0.7          # اختيار الصور
  uuid: ^4.2.2                  # معرفات فريدة
  cupertino_icons: ^1.0.8       # أيقونات iOS

  # مراقبة الأخطاء
  sentry_flutter: ^8.9.0        # تتبع الأخطاء

  # تحسينات الأداء
  flutter_cache_manager: ^3.3.3 # إدارة الذاكرة
  sqflite: ^2.3.3+1             # قاعدة بيانات محلية احتياطية

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0         # قواعد الكود
  mockito: ^5.4.4               # اختبارات الوحدة
  build_runner: ^2.4.13         # توليد الكود
  json_annotation: ^4.9.0       # JSON serialization
  test: ^1.25.8                 # مكتبة اختبارات إضافية
  fake_cloud_firestore: ^3.0.3  # محاكاة Firestore للاختبارات
  firebase_auth_mocks: ^0.14.1  # محاكاة Auth للاختبارات

flutter:
  uses-material-design: true

  # الأصول (Assets)
  assets:
    - assets/images/
    - assets/icons/
    - assets/logos/
    - assets/fonts/
    - assets/animations/         # للرسوم المتحركة
    - assets/sounds/             # لأصوات الإشعارات

  # الخطوط المخصصة
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Cairo-Light.ttf
          weight: 300
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Regular.ttf
        - asset: assets/fonts/Tajawal-Bold.ttf
          weight: 700
        - asset: assets/fonts/Tajawal-Light.ttf
          weight: 300