// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUNz98PVFsh4bcrG8_sF_6MIjA6mBU-7Q',
    appId: '1:813225046455:web:placeholderwebappid',
    messagingSenderId: '813225046455',
    projectId: 'dayenmadeen-ce109',
    authDomain: 'dayenmadeen-ce109.firebaseapp.com',
    storageBucket: 'dayenmadeen-ce109.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUNz98PVFsh4bcrG8_sF_6MIjA6mBU-7Q',
    appId: '1:813225046455:android:6d58d005a5446251d0b832',
    messagingSenderId: '813225046455',
    projectId: 'dayenmadeen-ce109',
    storageBucket: 'dayenmadeen-ce109.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUNz98PVFsh4bcrG8_sF_6MIjA6mBU-7Q',
    appId: '1:813225046455:ios:1a18d8b9cc71520cd0b832',
    messagingSenderId: '813225046455',
    projectId: 'dayenmadeen-ce109',
    storageBucket: 'dayenmadeen-ce109.appspot.com',
    iosBundleId: 'com.example.dayenMadeen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUNz98PVFsh4bcrG8_sF_6MIjA6mBU-7Q',
    appId: '1:813225046455:ios:1a18d8b9cc71520cd0b832',
    messagingSenderId: '813225046455',
    projectId: 'dayenmadeen-ce109',
    storageBucket: 'dayenmadeen-ce109.appspot.com',
    iosBundleId: 'com.example.dayenMadeen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUNz98PVFsh4bcrG8_sF_6MIjA6mBU-7Q',
    appId: '1:813225046455:web:placeholderwebappid',
    messagingSenderId: '813225046455',
    projectId: 'dayenmadeen-ce109',
    authDomain: 'dayenmadeen-ce109.firebaseapp.com',
    storageBucket: 'dayenmadeen-ce109.appspot.com',
  );
}
